version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DEBUG: 1
    volumes:
      - ./:/var/www/html/wp-content/plugins/contact-form-rest-api

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example