version: '3.1'

services:

  wordpress:
    build: ./wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DEBUG: 1
    volumes:
      - ./:/var/www/html/wp-content/plugins/contact-form-rest-api

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

      